name: Rust Release

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Install tarpaulin
      run: cargo install cargo-tarpaulin

    - name: Cache cargo registry
      uses: actions/cache@v4
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-registry-

    - name: Cache cargo index
      uses: actions/cache@v4
      with:
        path: ~/.cargo/git
        key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-index-

    - name: Cache cargo build
      uses: actions/cache@v4
      with:
        path: target
        key: ${{ runner.os }}-cargo-build-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-build-

    - name: Run Code Coverage
      env:
        RUSTFLAGS: "--deny warnings"
      run: cargo tarpaulin --out lcov --fail-immediately --release --fail-under 50 --force-clean

    - name: Upload Code Coverage
      uses: actions/upload-artifact@v4
      with:
        name: coverage
        path: lcov.info
        overwrite: true
        if-no-files-found: error
      
    - name: Build in release mode
      env:
        RUSTFLAGS: "--deny warnings"
      run:
        if [ "${GITHUB_REF_TYPE}" = "tag" ]; then
          VERSION=${GITHUB_REF_NAME}
        else
          VERSION=${GITHUB_SHA::8}
        fi
        cargo build --release --config package.version="${VERSION}"
  publish:
    if: contains(github.ref, 'main') # Only publish when on main branch.
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Publish to crates.io
      env:
        CRATES_IO_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
      run: 
        if [ "${GITHUB_REF_TYPE}" = "tag" ]; then
          VERSION=${GITHUB_REF_NAME}
        else
          VERSION=${GITHUB_SHA::8}
        fi
        cargo publish --token $CRATES_IO_TOKEN --config package.version="${VERSION}"